import type { FormAnswers } from '@reto/shared';
import type { ReviewReportRequest, CorrectReportRequest } from '@reto/shared';
import prisma from '@reto/db';
import type { ComputedRisk } from '../risk-engine/risk-engine.service';
import { riskEngineService } from '../risk-engine/risk-engine.service';
import { reportsModel } from './reports.model';
import { assertEvaluationFormComplete } from '../form-execution/form-completeness';
import { notificationsService } from '../notifications/notifications.service';
import { ApiError } from '@/lib/common/ApiError';
import {
  DEFAULT_PARTIAL_SECTIONS,
  correctionWasSaved,
  narrativeChanges,
  normalizeSectionId,
  reopenStaleCorrection,
} from './correction-policy';

/**
 * reports.service.ts
 * ---------------------------------------------------------------------------
 * Lógica de negocio de RF-16 (informe autogenerado), RF-17 (revisión) y
 * RF-18 (correcciones). Sección 14 de API_CONTRACTS.md.
 * ---------------------------------------------------------------------------
 */

interface AutoGenerateContext {
  institutionName: string;
  evaluationDate: Date;
  risk: ComputedRisk;
  answers: FormAnswers;
}

/**
 * ⚠️ ASUNCIÓN DE NEGOCIO: el contrato dice que el informe "se genera
 * automáticamente a partir de la evaluación" pero no especifica la
 * redacción. Se arma un texto base a partir de las respuestas NC/CP y el
 * puntaje de riesgo, que el técnico puede luego ajustar vía
 * POST /reports/:id/correct (tras una devolución del coordinador).
 */
function buildAutoGeneratedContent(ctx: AutoGenerateContext) {
  const noConformes = ctx.answers.filter((a) => a.value === 'NC');
  const parciales = ctx.answers.filter((a) => a.value === 'CP');

  const resumenEjecutivo =
    `Evaluation of ${ctx.institutionName} conducted on ${ctx.evaluationDate.toLocaleDateString('en-US')}. ` +
    `Risk level: ${ctx.risk.nivelRiesgo} (${ctx.risk.porcentajeCumplimiento}% compliance). ` +
    `Recommended inspection frequency: ${ctx.risk.frecuenciaInspeccion}.`;

  const hallazgos =
    [...noConformes, ...parciales]
      .map((a) => `- [${a.value}] ${a.txt}`)
      .join('\n') || 'No relevant findings recorded; all evaluated points are compliant.';

  const noConformidades =
    noConformes.map((a) => `- ${a.txt}`).join('\n') || 'No non-conformities recorded.';

  const recomendaciones =
    ctx.risk.nivelRiesgo === 'ALTO'
      ? 'Immediate correction of the detected non-conformities and a reinspection in the short term are recommended.'
      : ctx.risk.nivelRiesgo === 'MEDIO'
        ? 'It is recommended to address the detected observations before the next scheduled inspection.'
        : 'It is recommended to maintain the good practices observed.';

  return { resumenEjecutivo, hallazgos, noConformidades, recomendaciones };
}

export const reportsService = {
  /** Invoked by form-execution.service.ts when an evaluation is finalized. */
  autoGenerate: async (evaluationId: number, ctx: AutoGenerateContext) => {
    const content = buildAutoGeneratedContent(ctx);
    return reportsModel.create(evaluationId, content);
  },

  getByEvaluationId: async (evaluationId: number) => {
    await reopenStaleCorrection(evaluationId);
    const report = await reportsModel.getByEvaluationId(evaluationId);
    if (!report) throw ApiError.notFound('This evaluation does not yet have a generated report');
    return report;
  },

  getById: async (reportId: number) => {
    const report = await reportsModel.getById(reportId);
    if (!report) throw ApiError.notFound('Report not found');
    return report;
  },

  submit: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'BORRADOR') {
      throw ApiError.conflict(
        report.status === 'EN_CORRECCION' || report.status === 'DEVUELTO'
          ? 'This evaluation was returned for correction. Resubmit it after saving the requested changes.'
          : 'The report is not in a state that allows submission',
      );
    }
    await assertEvaluationFormComplete(report.evaluationId);
    const evaluation = await evaluationContext(report.evaluationId);
    return reportsModel.publish(reportId, evaluation.evaluationId, evaluation.caseId, { closeCorrection: false });
  },

  review: async (reportId: number, coordinatorId: number, body: ReviewReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'ENVIADO') {
      throw ApiError.conflict('Only reports awaiting review can be approved or returned');
    }

    const evaluation = await evaluationContext(report.evaluationId);
    const { action, comments } = body;

    if (action === 'APROBAR') {
      return reportsModel.approve(reportId, evaluation.evaluationId, evaluation.caseId, coordinatorId, comments);
    }

    const feedback = comments?.trim() ?? '';
    if (feedback.length < 3) {
      throw ApiError.validation('Explain what the evaluator must correct');
    }

    const full = action === 'DEVOLVER' || body.fullResubmission === true;
    let flaggedSections: string[] | null = null;
    if (!full) {
      if (body.flaggedSections && body.flaggedSections.length > 0) {
        const normalized = body.flaggedSections.map(normalizeSectionId);
        if (normalized.some((section) => !section)) {
          throw ApiError.validation('One or more flagged sections are not recognized');
        }
        flaggedSections = [...new Set(normalized as string[])];
      } else {
        flaggedSections = [...DEFAULT_PARTIAL_SECTIONS];
      }
    }

    const updated = await reportsModel.returnForCorrection(reportId, evaluation.evaluationId, evaluation.caseId, {
      coordinatorId,
      action,
      comments: feedback,
      correctionScope: full ? 'COMPLETA' : 'PARCIAL',
      flaggedSections,
    });

    const scopeText = full
      ? 'The same evaluation is open for a full resubmission. Previous answers, evidence, and notes are still there.'
      : 'Correct only the flagged sections. The rest of the assessment stays as submitted.';
    try {
      await notificationsService.notify(
        evaluation.technicianId,
        `Evaluation #${evaluation.evaluationId} returned for correction`,
        `${feedback} ${scopeText}`,
      );
    } catch {
      // The return itself already succeeded. A notification failure must not roll it back.
    }

    return updated;
  },

  getReviews: async (reportId: number) => {
    await reportsService.getById(reportId);
    return reportsModel.getReviews(reportId);
  },

  correct: async (reportId: number, data: CorrectReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.locked || report.status === 'ENVIADO' || report.status === 'APROBADO') {
      throw ApiError.forbidden('This report is locked. It can be edited again only after the coordinator returns it for correction.');
    }
    if (report.status !== 'BORRADOR' && report.status !== 'EN_CORRECCION' && report.status !== 'DEVUELTO') {
      throw ApiError.conflict('The report is not open for editing');
    }

    const changes = narrativeChanges(report, data);
    if (Object.keys(changes).length === 0) {
      throw ApiError.validation(
        report.status === 'BORRADOR'
          ? 'Change the report text before saving.'
          : 'Update at least one flagged section before saving the correction.',
      );
    }

    const returned = report.status === 'EN_CORRECCION' || report.status === 'DEVUELTO';
    return reportsModel.correct(reportId, changes, {
      incrementVersion: true,
      markSaved: returned,
    });
  },

  resend: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'EN_CORRECCION' && report.status !== 'DEVUELTO') {
      throw ApiError.conflict('The report is not in correction status');
    }
    if (!correctionWasSaved(report)) {
      throw ApiError.conflict('Save the requested correction before resubmitting this evaluation.');
    }
    const { answers } = await assertEvaluationFormComplete(report.evaluationId);
    await riskEngineService.computeAndPersist(report.evaluationId, answers);
    const evaluation = await evaluationContext(report.evaluationId);
    return reportsModel.publish(reportId, evaluation.evaluationId, evaluation.caseId, { closeCorrection: true });
  },
};

async function evaluationContext(evaluationId: number) {
  const evaluation = await prisma.evaluation.findUnique({
    where: { evaluationId },
    select: { evaluationId: true, caseId: true, technicianId: true, formResponseId: true },
  });
  if (!evaluation) throw ApiError.notFound('Evaluation not found');
  return evaluation;
}
