import type { FormAnswers, OfficialVerdictPreview, ReportNarrativeField, VerdictDelivery } from '@reto/shared';
import { REPORT_NARRATIVE_SECTIONS, assessFormCompleteness } from '@reto/shared';
import type { ReviewReportRequest, CorrectReportRequest } from '@reto/shared';
import prisma, { type Prisma } from '@reto/db';
import type { ComputedRisk } from '../risk-engine/risk-engine.service';
import { riskEngineService } from '../risk-engine/risk-engine.service';
import { riskEngineModel } from '../risk-engine/risk-engine.model';
import { reportsModel } from './reports.model';
import { readAnswers } from '../form-execution/form-execution.model';
import { assertEvaluationFormComplete, loadEvaluationForm } from '../form-execution/form-completeness';
import { notificationsService } from '../notifications/notifications.service';
import { notifyInstitution } from '../lifecycle/request-lifecycle';
import { renderOperationalEmail } from '@/lib/mail/email-layout';
import { ApiError } from '@/lib/common/ApiError';
import {
  DEFAULT_PARTIAL_SECTIONS,
  correctionWasSaved,
  narrativeChanges,
  normalizeSectionId,
  reopenStaleCorrection,
} from './correction-policy';

/**
 * reports.service.ts
 * ---------------------------------------------------------------------------
 * Lógica de negocio de RF-16 (informe autogenerado), RF-17 (revisión) y
 * RF-18 (correcciones). Sección 14 de API_CONTRACTS.md.
 * ---------------------------------------------------------------------------
 */

interface AutoGenerateContext {
  institutionName: string;
  evaluationDate: Date;
  risk: ComputedRisk | null;
  answers: FormAnswers;
}

/**
 * ⚠️ ASUNCIÓN DE NEGOCIO: el contrato dice que el informe "se genera
 * automáticamente a partir de la evaluación" pero no especifica la
 * redacción. Se arma un texto base a partir de las respuestas NC/CP y el
 * puntaje de riesgo, que el técnico puede luego ajustar vía
 * POST /reports/:id/correct (tras una devolución del coordinador).
 */
type NarrativeContent = Record<ReportNarrativeField, string>;

function findingLine(answer: FormAnswers[number], withValue: boolean) {
  const note = answer.note?.trim();
  const head = withValue ? `- [${answer.value}] ${answer.txt}` : `- ${answer.txt}`;
  return note ? `${head} — ${note}` : head;
}

function buildAutoGeneratedContent(ctx: AutoGenerateContext & { answered?: number; required?: number }): NarrativeContent {
  const noConformes = ctx.answers.filter((a) => a.value === 'NC');
  const parciales = ctx.answers.filter((a) => a.value === 'CP');

  if (!ctx.risk) {
    const answered = ctx.answered ?? ctx.answers.length;
    const required = ctx.required ?? ctx.answers.length;
    return {
      resumenEjecutivo:
        `Evaluation of ${ctx.institutionName} is still in progress (${answered} of ${required} required criteria answered). ` +
        'No official risk level has been issued yet.',
      hallazgos:
        [...noConformes, ...parciales].map((answer) => findingLine(answer, true)).join('\n') ||
        'No findings recorded yet.',
      noConformidades: noConformes.map((answer) => findingLine(answer, false)).join('\n') || 'No non-conformities recorded yet.',
      recomendaciones: 'Complete the required chapters before this verdict can be sent to the coordinator.',
    };
  }

  const resumenEjecutivo =
    `Evaluation of ${ctx.institutionName} conducted on ${ctx.evaluationDate.toLocaleDateString('en-US')}. ` +
    `Risk level: ${ctx.risk.nivelRiesgo} (${ctx.risk.porcentajeCumplimiento}% compliance). ` +
    `Recommended inspection frequency: ${ctx.risk.frecuenciaInspeccion}.`;

  const hallazgos =
    [...noConformes, ...parciales].map((answer) => findingLine(answer, true)).join('\n') ||
    'No relevant findings recorded; all evaluated points are compliant.';

  const noConformidades =
    noConformes.map((answer) => findingLine(answer, false)).join('\n') || 'No non-conformities recorded.';

  const recomendaciones =
    ctx.risk.nivelRiesgo === 'ALTO'
      ? 'Immediate correction of the detected non-conformities and a reinspection in the short term are recommended.'
      : ctx.risk.nivelRiesgo === 'MEDIO'
        ? 'It is recommended to address the detected observations before the next scheduled inspection.'
        : 'It is recommended to maintain the good practices observed.';

  return { resumenEjecutivo, hallazgos, noConformidades, recomendaciones };
}

function readAutoNarrative(raw: unknown): NarrativeContent | null {
  if (!raw || typeof raw !== 'object') return null;
  const source = raw as Record<string, unknown>;
  const snapshot = {} as NarrativeContent;
  for (const section of REPORT_NARRATIVE_SECTIONS) {
    const value = source[section.field];
    if (typeof value !== 'string') return null;
    snapshot[section.field] = value;
  }
  return snapshot;
}

function answerSignature(answers: FormAnswers) {
  return answers
    .map((answer) => `${answer.key}|${answer.value}|${(answer.note ?? '').trim()}`)
    .sort()
    .join('\n');
}

function evidenceAskKey(evidence: {
  h1AskId?: number | null;
  h2AskId?: number | null;
  h3AskId?: number | null;
  h4AskId?: number | null;
}) {
  if (evidence.h1AskId) return `h1_ask:${evidence.h1AskId}`;
  if (evidence.h2AskId) return `h2_ask:${evidence.h2AskId}`;
  if (evidence.h3AskId) return `h3_ask:${evidence.h3AskId}`;
  if (evidence.h4AskId) return `h4_ask:${evidence.h4AskId}`;
  return null;
}

interface VerdictEvaluation {
  evaluationId: number;
  status: string;
  technicianId: number;
  scheduledDate: Date;
  institution: { name: string; rnc?: string | null; streetName?: string | null };
  technician?: { person?: { name?: string | null; cedula?: string | null } | null } | null;
  formResponse: { answers: Prisma.JsonValue } | null;
  evidences: Array<{
    evidenceId: number;
    type: string;
    fileUrl: string;
    comment: string | null;
    latitude: number | null;
    longitude: number | null;
    h1AskId: number | null;
    h2AskId: number | null;
    h3AskId: number | null;
    h4AskId: number | null;
  }>;
}

/**
 * Narrative the coordinator will receive.
 * Auto-generated sections follow the current answers. A section the inspector
 * edited by hand is sent as saved.
 */
async function composeVerdict(
  evaluation: VerdictEvaluation,
  liveAnswers: FormAnswers | undefined,
  requester: { userId: number; role: string },
): Promise<OfficialVerdictPreview & { scopedAnswers: FormAnswers; nextAuto: NarrativeContent | null }> {
  await reopenStaleCorrection(evaluation.evaluationId);
  const report = await reportsModel.getByEvaluationId(evaluation.evaluationId);
  const evaluationStatus =
    report && (report.status === 'EN_CORRECCION' || report.status === 'DEVUELTO')
      ? 'EN_CORRECCION'
      : evaluation.status;

  const stored = readAnswers(evaluation.formResponse?.answers);
  const editable = evaluationStatus === 'EN_PROCESO' || evaluationStatus === 'EN_CORRECCION';
  const assigned =
    requester.role === 'ADMIN' ||
    (requester.role === 'TECNICO_EVALUADOR' && evaluation.technicianId === requester.userId);
  const useLive = Boolean(editable && assigned && liveAnswers);
  const source = useLive ? liveAnswers! : stored;

  const loaded = await loadEvaluationForm(evaluation.evaluationId);
  const completeness = loaded?.template
    ? assessFormCompleteness(loaded.template, source, loaded.context)
    : null;
  const applicable = new Set(completeness?.applicableKeys ?? source.map((answer) => answer.key));
  const scoped = source.filter((answer) => applicable.has(answer.key));
  const byKey = new Map(scoped.map((answer) => [answer.key, answer]));

  const locked = Boolean(report && (report.locked || report.status === 'ENVIADO' || report.status === 'APROBADO'));
  let score: ComputedRisk | null = null;
  if (locked) {
    score = await riskEngineModel.getScoreByEvaluation(evaluation.evaluationId);
  }
  if (!score) {
    score = await riskEngineService.calculate(scoped);
  }

  const generated = buildAutoGeneratedContent({
    institutionName: evaluation.institution.name,
    evaluationDate: evaluation.scheduledDate,
    risk: score,
    answers: scoped,
    answered: completeness?.answeredQuestions ?? scoped.length,
    required: completeness?.requiredQuestions ?? scoped.length,
  });

  let narrative = generated;
  let editedSections: string[] = [];
  let nextAuto: NarrativeContent | null = generated;
  if (report) {
    if (locked) {
      narrative = {
        resumenEjecutivo: report.resumenEjecutivo,
        hallazgos: report.hallazgos,
        noConformidades: report.noConformidades,
        recomendaciones: report.recomendaciones,
      };
      nextAuto = readAutoNarrative(report.autoNarrative);
    } else {
      const auto = readAutoNarrative(report.autoNarrative) ?? (report.version === 1 ? {
        resumenEjecutivo: report.resumenEjecutivo,
        hallazgos: report.hallazgos,
        noConformidades: report.noConformidades,
        recomendaciones: report.recomendaciones,
      } : null);
      narrative = { ...generated };
      nextAuto = { ...(auto ?? generated) };
      editedSections = [];
      for (const section of REPORT_NARRATIVE_SECTIONS) {
        const stillAuto = auto ? report[section.field] === auto[section.field] : report[section.field] === generated[section.field];
        if (stillAuto) {
          narrative[section.field] = generated[section.field];
          nextAuto[section.field] = generated[section.field];
        } else {
          narrative[section.field] = report[section.field];
          if (auto) nextAuto[section.field] = auto[section.field];
          editedSections.push(section.label);
        }
      }
    }
  }

  const questions = completeness?.chapters.flatMap((chapter) =>
    chapter.status === 'not_applicable'
      ? []
      : chapter.questions.map((question) => {
          const answer = byKey.get(question.key);
          return {
            key: question.key,
            chapter: chapter.name,
            code: question.codeLabel,
            text: question.txt,
            value: answer?.value ?? null,
            note: answer?.note?.trim() || null,
          };
        }),
  ) ?? scoped.map((answer) => ({
    key: answer.key,
    chapter: 'Assessment',
    code: answer.key,
    text: answer.txt,
    value: answer.value,
    note: answer.note?.trim() || null,
  }));

  const ready = Boolean(score && (completeness?.canSubmit ?? scoped.length > 0));
  let delivery: VerdictDelivery = 'working';
  if (report?.status === 'APROBADO') delivery = 'approved';
  else if (locked) delivery = 'with_coordinator';
  else if (ready) delivery = 'ready_to_send';

  const inCorrection = evaluationStatus === 'EN_CORRECCION';

  return {
    delivery,
    pendingLocalChanges: useLive && answerSignature(source) !== answerSignature(stored),
    correctionReady: inCorrection && report ? correctionWasSaved(report) : null,
    evaluationStatus,
    scheduledDate: evaluation.scheduledDate.toISOString(),
    establishment: {
      name: evaluation.institution.name,
      rnc: evaluation.institution.rnc ?? null,
      address: evaluation.institution.streetName ?? null,
    },
    inspector: {
      name: evaluation.technician?.person?.name ?? null,
      cedula: evaluation.technician?.person?.cedula ?? null,
    },
    reportId: report?.reportId ?? null,
    reportStatus: report?.status ?? null,
    reportVersion: report?.version ?? null,
    answeredQuestions: completeness?.answeredQuestions ?? scoped.length,
    requiredQuestions: completeness?.requiredQuestions ?? scoped.length,
    narrative,
    editedSections,
    score: score
      ? {
          porcentajeCumplimiento: score.porcentajeCumplimiento,
          puntajeObtenido: score.puntajeObtenido,
          nivelRiesgo: score.nivelRiesgo,
          frecuenciaInspeccion: score.frecuenciaInspeccion,
        }
      : null,
    entries: questions,
    evidences: evaluation.evidences.map((evidence) => ({
      evidenceId: evidence.evidenceId,
      type: evidence.type,
      comment: evidence.comment,
      fileName: evidence.fileUrl.split('/').pop() || null,
      latitude: evidence.latitude,
      longitude: evidence.longitude,
      askKey: evidenceAskKey(evidence),
    })),
    scopedAnswers: scoped,
    nextAuto,
  };
}

/** Rewrites auto-generated sections from the saved answers before the coordinator receives the report. */
async function persistOutgoingNarrative(evaluationId: number, reportId: number) {
  const { answers } = await assertEvaluationFormComplete(evaluationId);
  await riskEngineService.computeAndPersist(evaluationId, answers);
  const current = await prisma.evaluation.findUniqueOrThrow({
    where: { evaluationId },
    include: {
      institution: { select: { name: true, rnc: true, streetName: true } },
      technician: { select: { person: { select: { name: true, cedula: true } } } },
      formResponse: { select: { answers: true } },
      evidences: true,
    },
  });
  const verdict = await composeVerdict(
    {
      evaluationId: current.evaluationId,
      status: current.status,
      technicianId: current.technicianId,
      scheduledDate: current.scheduledDate,
      institution: current.institution,
      technician: current.technician,
      formResponse: current.formResponse,
      evidences: current.evidences,
    },
    undefined,
    { userId: current.technicianId, role: 'TECNICO_EVALUADOR' },
  );
  if (verdict.nextAuto) {
    await reportsModel.syncNarrative(reportId, verdict.narrative, verdict.nextAuto);
  }
}

export const reportsService = {
  /** Invoked by form-execution.service.ts when an evaluation is finalized. */
  autoGenerate: async (evaluationId: number, ctx: AutoGenerateContext) => {
    const content = buildAutoGeneratedContent(ctx);
    return reportsModel.create(evaluationId, content);
  },

  /**
   * Official verdict as the coordinator will receive it.
   * Field inspectors may pass the answers currently on screen.
   */
  preview: async (
    evaluation: VerdictEvaluation,
    liveAnswers: FormAnswers | undefined,
    requester: { userId: number; role: string },
  ) => {
    const verdict = await composeVerdict(evaluation, liveAnswers, requester);
    const { scopedAnswers: _scoped, nextAuto: _auto, ...preview } = verdict;
    return preview;
  },

  getByEvaluationId: async (evaluationId: number) => {
    await reopenStaleCorrection(evaluationId);
    const report = await reportsModel.getByEvaluationId(evaluationId);
    if (!report) throw ApiError.notFound('This evaluation does not yet have a generated report');
    return report;
  },

  getById: async (reportId: number) => {
    const report = await reportsModel.getById(reportId);
    if (!report) throw ApiError.notFound('Report not found');
    return report;
  },

  submit: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'BORRADOR') {
      throw ApiError.conflict(
        report.status === 'EN_CORRECCION' || report.status === 'DEVUELTO'
          ? 'This evaluation was returned for correction. Resubmit it after saving the requested changes.'
          : 'The report is not in a state that allows submission',
      );
    }
    await persistOutgoingNarrative(report.evaluationId, reportId);
    const evaluation = await evaluationContext(report.evaluationId);
    return reportsModel.publish(reportId, evaluation.evaluationId, evaluation.caseId, { closeCorrection: false });
  },

  review: async (reportId: number, coordinatorId: number, body: ReviewReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'ENVIADO') {
      throw ApiError.conflict('Only reports awaiting review can be approved or returned');
    }

    const evaluation = await evaluationContext(report.evaluationId);
    const { action, comments } = body;

    if (action === 'APROBAR') {
      const approved = await reportsModel.approve(reportId, evaluation.evaluationId, evaluation.caseId, coordinatorId, comments);
      const requestId = evaluation.case?.bpmRequest?.bpmRequestId;
      await notifyInstitution(
        evaluation.institutionId,
        requestId ? `BPM request #${requestId} approved` : `Evaluation #${evaluation.evaluationId} approved`,
        requestId
          ? `The coordinator approved BPM request #${requestId}. The decision is now visible in your company portal.`
          : `The coordinator approved evaluation #${evaluation.evaluationId}. The decision is now visible in your company portal.`,
        evaluation.case?.bpmRequest?.createdById ? [evaluation.case.bpmRequest.createdById] : [],
      );
      return approved;
    }

    const feedback = comments?.trim() ?? '';
    if (feedback.length < 3) {
      throw ApiError.validation('Explain what the evaluator must correct');
    }

    const full = action === 'DEVOLVER' || body.fullResubmission === true;
    let flaggedSections: string[] | null = null;
    if (!full) {
      if (body.flaggedSections && body.flaggedSections.length > 0) {
        const normalized = body.flaggedSections.map(normalizeSectionId);
        if (normalized.some((section) => !section)) {
          throw ApiError.validation('One or more flagged sections are not recognized');
        }
        flaggedSections = [...new Set(normalized as string[])];
      } else {
        flaggedSections = [...DEFAULT_PARTIAL_SECTIONS];
      }
    }

    const updated = await reportsModel.returnForCorrection(reportId, evaluation.evaluationId, evaluation.caseId, {
      coordinatorId,
      action,
      comments: feedback,
      correctionScope: full ? 'COMPLETA' : 'PARCIAL',
      flaggedSections,
    });

    const scopeText = full
      ? 'The same evaluation is open for a full resubmission. Previous answers, evidence, and notes are still there.'
      : 'Correct only the flagged sections. The rest of the assessment stays as submitted.';
    try {
      await notificationsService.notify(
        evaluation.technicianId,
        `Evaluation #${evaluation.evaluationId} returned for correction`,
        `${feedback} ${scopeText}`,
        renderOperationalEmail({
          heading: 'An evaluation was returned for correction',
          paragraphs: [scopeText],
          details: [
            { label: 'Evaluation', value: `#${evaluation.evaluationId}` },
            { label: 'What to correct', value: feedback },
            { label: 'Scope', value: full ? 'Full resubmission' : 'Flagged sections only' },
          ],
          footnote: 'Sign in to RADAR, open the field assessment, and resubmit after the requested changes.',
        }),
      );
      const requestId = evaluation.case?.bpmRequest?.bpmRequestId;
      await notifyInstitution(
        evaluation.institutionId,
        requestId ? `BPM request #${requestId} returned for correction` : `Evaluation #${evaluation.evaluationId} returned for correction`,
        'The coordinator returned the evaluation for correction. It is not approved yet.',
        evaluation.case?.bpmRequest?.createdById ? [evaluation.case.bpmRequest.createdById] : [],
      );
    } catch {
      // The return itself already succeeded. A notification failure must not roll it back.
    }

    return updated;
  },

  getReviews: async (reportId: number) => {
    await reportsService.getById(reportId);
    return reportsModel.getReviews(reportId);
  },

  correct: async (reportId: number, data: CorrectReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.locked || report.status === 'ENVIADO' || report.status === 'APROBADO') {
      throw ApiError.forbidden('This report is locked. It can be edited again only after the coordinator returns it for correction.');
    }
    if (report.status !== 'BORRADOR' && report.status !== 'EN_CORRECCION' && report.status !== 'DEVUELTO') {
      throw ApiError.conflict('The report is not open for editing');
    }

    const changes = narrativeChanges(report, data);
    if (Object.keys(changes).length === 0) {
      throw ApiError.validation(
        report.status === 'BORRADOR'
          ? 'Change the report text before saving.'
          : 'Update at least one flagged section before saving the correction.',
      );
    }

    const returned = report.status === 'EN_CORRECCION' || report.status === 'DEVUELTO';
    return reportsModel.correct(reportId, changes, {
      incrementVersion: true,
      markSaved: returned,
    });
  },

  resend: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'EN_CORRECCION' && report.status !== 'DEVUELTO') {
      throw ApiError.conflict('The report is not in correction status');
    }
    if (!correctionWasSaved(report)) {
      throw ApiError.conflict('Save the requested correction before resubmitting this evaluation.');
    }
    await persistOutgoingNarrative(report.evaluationId, reportId);
    const evaluation = await evaluationContext(report.evaluationId);
    return reportsModel.publish(reportId, evaluation.evaluationId, evaluation.caseId, { closeCorrection: true });
  },
};

async function evaluationContext(evaluationId: number) {
  const evaluation = await prisma.evaluation.findUnique({
    where: { evaluationId },
    select: {
      evaluationId: true,
      caseId: true,
      technicianId: true,
      institutionId: true,
      formResponseId: true,
      case: { select: { bpmRequest: { select: { bpmRequestId: true, createdById: true } } } },
    },
  });
  if (!evaluation) throw ApiError.notFound('Evaluation not found');
  return evaluation;
}
