import type { AskAnswer } from '@reto/shared';
import type { ReviewReportRequest, CorrectReportRequest } from '@reto/shared';
import type { ComputedRisk } from '../risk-engine/risk-engine.service';
import { reportsModel } from './reports.model';
import { ApiError } from '@/lib/common/ApiError';

/**
 * reports.service.ts
 * ---------------------------------------------------------------------------
 * Lógica de negocio de RF-16 (informe autogenerado), RF-17 (revisión) y
 * RF-18 (correcciones). Sección 14 de API_CONTRACTS.md.
 * ---------------------------------------------------------------------------
 */

interface AutoGenerateContext {
  institutionName: string;
  evaluationDate: Date;
  risk: ComputedRisk;
  answers: AskAnswer[];
}

/**
 * ⚠️ ASUNCIÓN DE NEGOCIO: el contrato dice que el informe "se genera
 * automáticamente a partir de la evaluación" pero no especifica la
 * redacción. Se arma un texto base a partir de las respuestas NC/CP y el
 * puntaje de riesgo, que el técnico puede luego ajustar vía
 * POST /reports/:id/correct (tras una devolución del coordinador).
 */
function buildAutoGeneratedContent(ctx: AutoGenerateContext) {
  const noConformes = ctx.answers.filter((a) => a.value === 'NC');
  const parciales = ctx.answers.filter((a) => a.value === 'CP');

  const resumenEjecutivo =
    `Evaluación de ${ctx.institutionName} realizada el ${ctx.evaluationDate.toLocaleDateString('es-DO')}. ` +
    `Nivel de riesgo: ${ctx.risk.nivelRiesgo} (${ctx.risk.porcentajeCumplimiento}% de cumplimiento). ` +
    `Frecuencia de inspección recomendada: ${ctx.risk.frecuenciaInspeccion}.`;

  const hallazgos =
    [...noConformes, ...parciales]
      .map((a) => `- [${a.value}] ${a.askId}${a.observaciones ? `: ${a.observaciones}` : ''}`)
      .join('\n') || 'No se registraron hallazgos relevantes; todos los puntos evaluados cumplen.';

  const noConformidades =
    noConformes.map((a) => `- ${a.askId}${a.observaciones ? `: ${a.observaciones}` : ''}`).join('\n') ||
    'No se registraron no conformidades.';

  const recomendaciones =
    ctx.risk.nivelRiesgo === 'ALTO'
      ? 'Se recomienda corrección inmediata de las no conformidades detectadas y una reinspección en el corto plazo.'
      : ctx.risk.nivelRiesgo === 'MEDIO'
        ? 'Se recomienda subsanar las observaciones detectadas antes de la próxima inspección programada.'
        : 'Se recomienda mantener las buenas prácticas observadas.';

  return { resumenEjecutivo, hallazgos, noConformidades, recomendaciones };
}

export const reportsService = {
  /** Invocado por form-execution.service.ts al finalizar una evaluación. */
  autoGenerate: async (evaluationId: number, ctx: AutoGenerateContext) => {
    const content = buildAutoGeneratedContent(ctx);
    return reportsModel.create(evaluationId, content);
  },

  getByEvaluationId: async (evaluationId: number) => {
    const report = await reportsModel.getByEvaluationId(evaluationId);
    if (!report) throw ApiError.notFound('Esta evaluación todavía no tiene un informe generado');
    return report;
  },

  getById: async (reportId: number) => {
    const report = await reportsModel.getById(reportId);
    if (!report) throw ApiError.notFound('El informe no existe');
    return report;
  },

  submit: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'BORRADOR' && report.status !== 'EN_CORRECCION') {
      throw ApiError.conflict('El informe no está en un estado que permita enviarlo');
    }
    return reportsModel.updateStatus(reportId, 'ENVIADO', true);
  },

  review: async (reportId: number, coordinatorId: number, { action, comments }: ReviewReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'ENVIADO') {
      throw ApiError.conflict('Solo se pueden revisar informes en estado ENVIADO');
    }

    await reportsModel.addReview(reportId, coordinatorId, action, comments);

    if (action === 'APROBAR') {
      return reportsModel.updateStatus(reportId, 'APROBADO', true);
    }
    if (action === 'DEVOLVER') {
      return reportsModel.updateStatus(reportId, 'DEVUELTO', false);
    }
    // SOLICITAR_CORRECCION
    return reportsModel.updateStatus(reportId, 'EN_CORRECCION', false);
  },

  getReviews: async (reportId: number) => {
    await reportsService.getById(reportId);
    return reportsModel.getReviews(reportId);
  },

  correct: async (reportId: number, data: CorrectReportRequest) => {
    const report = await reportsService.getById(reportId);
    if (report.locked) {
      throw ApiError.forbidden('El informe está bloqueado; solo puede corregirse tras una devolución del coordinador');
    }
    return reportsModel.correct(reportId, data);
  },

  resend: async (reportId: number) => {
    const report = await reportsService.getById(reportId);
    if (report.status !== 'EN_CORRECCION' && report.status !== 'DEVUELTO') {
      throw ApiError.conflict('El informe no está en corrección');
    }
    return reportsModel.updateStatus(reportId, 'ENVIADO', true);
  },
};
